export default {
    ADD_NOTE: "ADD_NOTE",
    REMOVE_NOTE : "REMOVE_NOTE",
    UPDATE_NOTE:"UPDATE_NOTE",
    RESET_INPUT:"RESET_INPUT",

    SET_INPUT_TITLE :"SET_INPUT_TITLE",
    SET_INPUT_CONTENT :"SET_INPUT_CONTENT",
    SET_INPUT_ID :"SET_INPUT_ID",
}
